set(ALIRO_VERSION_MAJOR 1)
set(ALIRO_VERSION_MINOR 0)
set(ALIRO_VERSION_PATCH 0)
set(ALIRO_VERSION "${ALIRO_VERSION_MAJOR}.${ALIRO_VERSION_MINOR}.${ALIRO_VERSION_PATCH}")
set(ALIRO_SPEC_VERSION "1.0")

message(STATUS "Aliro library version: ${ALIRO_VERSION} (spec ${ALIRO_SPEC_VERSION})")
